version: 2.1.3-build{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
image: Visual Studio 2022
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
cache: '%USERPROFILE%\.nuget\packages -> **\*.csproj'
before_build:
- ps: msbuild /t:restore /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
build:
  verbosity: minimal
after_build:
- ps: msbuild /t:pack /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
artifacts:
- path: '**/*.nupkg'
deploy:
- provider: NuGet
  server: https://www.myget.org/F/zhaobang-ftpserver-nightly/api/v2/package
  api_key:
    secure: tRrj53sW6hpLkOYP9U4PJU9J/EQ2OmNCWrWgZhZ/eF6+DMoY+Ed/GUhG5P8lr8rV
  skip_symbols: true
  artifact: /.*(Zhaobang\.FtpServer\.).*nupkg/
  on:
    branch: master